stages:
  - build
  - deploy

docker-build:
  stage: build
  # Use the official docker image.
  image: docker:latest
  services:
    - docker:dind
  tags:
    - alpine-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Docker login successful"
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/motion-machine:latest

  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
  # Default branch is also tagged with `latest`
  script:
    - echo "Docker Image Name = $DOCKER_IMAGE_NAME"
    - docker build --pull -t "$DOCKER_IMAGE_NAME" .
    - docker push "$DOCKER_IMAGE_NAME"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "dev"'
      exists:
        - Dockerfile

docker-deploy:
  stage: deploy
  image: alpine:latest
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE/motion-machine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$SSH_HOST "docker pull $DOCKER_IMAGE_NAME && docker compose -f docker-compose.yml -p motion-machine up --remove-orphans --force-recreate -d && docker system prune -f"
  only:
    - main
    - dev
